services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    preDeployCommand: flask db upgrade
    startCommand: gunicorn app:app
    buildFilter:
      paths:
        - backend/
