services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    preDeployCommand: cd backend && flask db upgrade
    startCommand: cd backend && gunicorn app:app
