"""Add used_quantity to service_request_inventory

Revision ID: c57de073c8b8
Revises: d5dc3b70fd2d
Create Date: 2025-06-25 12:48:06.348691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57de073c8b8'
down_revision = 'd5dc3b70fd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_quantity', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_request_inventory', schema=None) as batch_op:
        batch_op.drop_column('used_quantity')

    # ### end Alembic commands ###
