"""Add threshold to the inventory table

Revision ID: d5dc3b70fd2d
Revises: c35c24032d24
Create Date: 2025-06-24 21:15:11.588465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5dc3b70fd2d'
down_revision = 'c35c24032d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('threshold')

    # ### end Alembic commands ###
